name: protoflutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  sqflite: ^2.4.2
  supabase_flutter: ^2.12.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logoApp.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
